// Generated by <a href="http://scalaxb.org/">scalaxb</a>.



case class CcmDataItems(CcmDataItem: CcmDataItem*)


case class CcmDataItem(componentId: Option[String] = None,
  readOnly: Option[Boolean] = None,
  before: Option[String] = None,
  after: Option[String] = None,
  errorCode: Option[Int] = None,
  errorMessage: Option[String] = None)


case class CcmUpdate(Links: Option[Links] = None,
  id: String,
  status: Option[String] = None,
  uecode: Option[String] = None,
  accountNumber: Option[String] = None,
  failureReason: Option[String] = None)


case class CcmUpdates(CcmUpdate: CcmUpdate*)


case class CcmAction(Links: Option[Links] = None,
  CcmUpdates: Option[CcmUpdates] = None,
  id: String,
  status: Option[String] = None,
  username: Option[String] = None,
  uecode: Option[String] = None,
  performed: Option[javax.xml.datatype.XMLGregorianCalendar] = None,
  failureReason: Option[String] = None)


case class CcmPageComponent(CcmDataItem: Option[CcmDataItem] = None,
  id: Option[String] = None,
  label: Option[String] = None,
  length: Option[Int] = None,
  defaultValue: Option[String] = None,
  mandatory: Option[Boolean] = None,
  text: Option[Boolean] = None,
  numeric: Option[Boolean] = None,
  displayType: Option[String] = None)


case class CcmPageComponents(CcmPageComponent: CcmPageComponent*)


case class CcmPage(Links: Option[Links] = None,
  CcmPageComponents: CcmPageComponents,
  id: Option[String] = None,
  description: Option[String] = None)


case class CcmPages(CcmPage: Seq[CcmPage] = Nil,
  templateId: Option[String] = None)


case class CcmActions(CcmAction: CcmAction*)


case class CcmTemplates(CcmTemplate: CcmTemplate*)

trait ModificationType

object ModificationType {
  def fromString(value: String, scope: scala.xml.NamespaceBinding): ModificationType = value match {
    case "*NEW" => U42NEW
    case "*UPD" => U42UPD
    case "*ADD" => U42ADD

  }
}

case object U42NEW extends ModificationType { override def toString = "*NEW" }
case object U42UPD extends ModificationType { override def toString = "*UPD" }
case object U42ADD extends ModificationType { override def toString = "*ADD" }

trait EntityLevel

object EntityLevel {
  def fromString(value: String, scope: scala.xml.NamespaceBinding): EntityLevel = value match {
    case "P" => P
    case "C" => C
    case "*" => U42

  }
}

case object P extends EntityLevel { override def toString = "P" }
case object C extends EntityLevel { override def toString = "C" }
case object U42 extends EntityLevel { override def toString = "*" }


case class CcmTemplate(Links: Option[Links] = None,
  CcmPages: CcmPages,
  id: Option[String] = None,
  description: Option[String] = None,
  personType: Option[String] = None,
  accountType: Option[String] = None,
  numberOfPages: Option[Int] = None,
  modificationType: Option[ModificationType] = None,
  entityLevel: Option[EntityLevel] = None)

