// Generated by <a href="http://scalaxb.org/">scalaxb</a>.



case class AddressLines(Line: String*)


case class Address(AddressLines: Option[AddressLines] = None,
  City: Option[String] = None,
  PostCode: Option[String] = None,
  Country: Option[Country] = None,
  Validity: Option[DateRange] = None,
  isPrimary: Option[Boolean] = None,
  yearsAtAddress: Option[Int] = None)


case class PhoneNumber(Validity: Option[DateRange] = None,
  typeValue: Option[String] = None,
  country: String,
  number: String,
  extension: Option[String] = None,
  isPrimary: Option[Boolean] = None)


/** A country.  ISO3 code is the unique identifier.
*/
case class Country(Description: Option[String] = None,
  iso3: Option[String] = None,
  iso2: Option[String] = None)


/** A monetary value
*/
case class CashValue(currency: String,
  amount: BigDecimal)


/** A date range
*/
case class DateRange(from: javax.xml.datatype.XMLGregorianCalendar,
  to: Option[javax.xml.datatype.XMLGregorianCalendar] = None)


case class EmailAddress(address: String,
  label: Option[String] = None)


case class EmailAddresses(EmailAddress: EmailAddress*)


case class Addresses(Address: Address*)


case class PhoneNumbers(PhoneNumber: PhoneNumber*)


case class Links(Link: Link*)


case class Parameters(Parameter: Parameter*)


case class Parameter(key: String,
  valueAttribute: String)


/** 
                The link shows further actions available on this resource
            
*/
case class Link(mixed: Seq[scalaxb.DataRecord[Any]] = Nil,
  href: Option[String] = None,
  rel: String,
  description: Option[String] = None)


case class ProductType(Description: Option[String] = None,
  code: String,
  typeValue: Option[String] = None)


case class Role(Description: Option[String] = None,
  croleId: Option[String] = None)


case class ValuationFormat(Description: Option[String] = None,
  id: Option[String] = None)


case class InvestmentObjective(Description: Option[String] = None,
  code: Option[String] = None)


case class InstrumentHeading(csedol: Option[String] = None,
  cisin: Option[String] = None,
  csymbol: Option[String] = None,
  cname: Option[String] = None,
  clongName: Option[String] = None,
  cmarket: Option[String] = None,
  csecurityType: Option[String] = None,
  country: Option[String] = None,
  abbreviation: Option[String] = None)


case class Price(cbid: Option[BigDecimal] = None,
  cmid: Option[BigDecimal] = None,
  cask: Option[BigDecimal] = None)


case class DeliveryType(inBox: Option[Boolean] = None,
  email: Option[Boolean] = None,
  sms: Option[Boolean] = None)


case class Error(Message: Option[String] = None,
  Info: Option[String] = None,
  httpCode: Option[Int] = None,
  jhcCode: Option[Int] = None)


case class Errors(Error: Error*)

