// Generated by <a href="http://scalaxb.org/">scalaxb</a>.



case class Company(Links: Option[Links] = None,
  uecode: Option[String] = None,
  name: Option[String] = None,
  registrationNumber: Option[String] = None,
  country: Option[String] = None)


case class CompanyRelationship(Company: Company,
  croleId: Option[String] = None)


case class CompanyRelationships(CompanyRelationship: CompanyRelationship*)

