// Generated by <a href="http://scalaxb.org/">scalaxb</a>.



/** A decimal value, represented by a 128bit significand and a scale
*/
case class Decimal(msb: Option[Long] = None,
  lsb: Option[Long] = None,
  scale: Int)

