// Generated by <a href="http://scalaxb.org/">scalaxb</a>.



case class FxRate(from: Option[String] = None,
  to: Option[String] = None,
  rate: Option[BigDecimal] = None)


case class FxTable(FxRate: Seq[FxRate] = Nil,
  mode: Option[String] = None)

