// Generated by <a href="http://scalaxb.org/">scalaxb</a>.



case class InstrumentClassification(sector: Option[String] = None,
  nationalityDeclaration: Option[Boolean] = None,
  industrialClassificationCode: Option[String] = None,
  marketSegment: Option[String] = None)


case class InstrumentApplicability(trading: Option[Boolean] = None,
  isaTrading: Option[Boolean] = None,
  sippTrading: Option[Boolean] = None,
  rspTrading: Option[Boolean] = None)


case class InstrumentProperties(countryOfIncorporation: Option[String] = None,
  issuerName: Option[String] = None,
  securityDescription: Option[String] = None,
  numberOfTrades: Option[Long] = None)


case class Instrument(InstrumentHeading: Option[InstrumentHeading] = None,
  InstrumentClassification: Option[InstrumentClassification] = None,
  InstrumentApplicability: Option[InstrumentApplicability] = None,
  InstrumentProperties: Option[InstrumentProperties] = None)


case class Instruments(Instrument: Instrument*)

