// Generated by <a href="http://scalaxb.org/">scalaxb</a>.



/** Contains any element
*/
case class Container(objectType: String,
  containedObject: scalaxb.Base64Binary)


case class ApiMessage(Parameters: Option[Parameters] = None,
  Body: Option[Container] = None,
  method: Option[String] = None,
  path: Option[String] = None,
  requestId: Option[String] = None,
  person: Option[String] = None,
  status: Option[Int] = None)

